### PR TITLE
Add smoke test for #289 Conflict with Prettier

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
Ref #289

### CODE REVIEW

**Comment by EvgenyOrekhov** [comment]
@NullVoxPopuli I added `issue-reproductions/289`, but got `issue-reproductions/195` failing.

**Comment by NullVoxPopuli** [comment]
Yeah, looks like a breaking change happened in one of the deps, I'll take it from here, thanks!

**Comment by NullVoxPopuli** [comment]
Thanks for getting this started!

**Pull request merged**
