### PR TITLE
adds eslint testing skeleton

### PR DESCRIPTION
**Pull request by basz**
hey

I honestly have now clue what to put exactly into folder 721. Tests dont run locally (macos) (find: -printf: unknown primary or operator). Ive use a utility to generate a 'flat' config, i think...

so pls consider this a nice try.. yet failed...

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Looks like we have:
```
PWD: /home/runner/work/eslint-plugin-decorator-position/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721
Invalid option '--eslintrc' - perhaps you meant '--ignore'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

Which means that the test runner scripts will need updated:
- https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/main/scripts/-pnpm.sh#L40
- and: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/main/scripts/-yarn.sh#L43

to probably have some `if eslint 9` check, and use the newer CLI args / flags

**Comment by tcjr** [comment]
> Tests dont run locally (macos) (find: -printf: unknown primary or operator)

The workaround for this on MacOS is to install GNU find, `gfind`, and update the script.

```
brew install gfind
```

Then in `smoke-test.sh`, update line 21:
```
  smoke_tests=$(gfind $TEST_DIR \
```

That should allow you to run it locally.

**Comment by basz** [comment]
`brew install findutils`, but yeah. thx!

**Comment by basz** [comment]
I *think* the only remaining peer dependancy that is failing currently for comes from https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/issues/721

a seconds test run with ./scripts/smoke-test.sh smoke-tests/issue-reproductions/721
Select Test: issue-reproductions/721

yield a different result that I'm having a hard time intepreting

```
Changing to smoke-tests/issue-reproductions/721
Running tests for smoke-tests/issue-reproductions/721 with pnpm


Linking to /Users/bas/Sandbox/eslint-plugin-decorator-position from smoke-tests/issue-reproductions/721
../../..                                 | +563 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
../../..                                 | Progress: resolved 563, reused 563, downloaded 0, added 0, done
 WARN  The package eslint-plugin-decorator-position, which you have just pnpm linked, has the following peerDependencies specified in its package.json:

  - @babel/eslint-parser@^7.18.2,   - eslint@^6.0.0 || ^7.31.0 || ^8.0.0

The linked in dependency will not resolve the peer dependencies from the target node_modules.
This might cause issues in your project. To resolve this, you may use the "file:" protocol to reference the local dependency.

dependencies:
+ eslint-plugin-decorator-position 5.0.2 <- ../../..
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 324ms


Legend: production dependency, optional only, dev only

test@0.0.0 /Users/bas/Sandbox/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721

dependencies:
eslint 9.10.0
Legend: production dependency, optional only, dev only

test@0.0.0 /Users/bas/Sandbox/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721

dependencies:
prettier 3.3.2
/Users/bas/Sandbox/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721/node_modules/.bin
/Users/bas/Sandbox/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721/node_modules/.bin


PWD: /Users/bas/Sandbox/eslint-plugin-decorator-position/smoke-tests/issue-reproductions/721
Invalid option '--eslintrc' - perhaps you meant '--ignore'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

**Comment by NullVoxPopuli** [comment]
Doh, looks like ci broke. I'll fix, then we can rebase

**Comment by NullVoxPopuli** [comment]
now ready for rebase -- CI should start running properly, so we can get more meaningful info from it

**Comment by NullVoxPopuli** [comment]
Does ESLint9 only support node 18?

looks like: 
image


so, we'll need to skip the matrix scenarios for eslint 9 < node 18

**Comment by NullVoxPopuli** [comment]
I'm extracting the CI changes here: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/726 -- and then I can also try to make the peer situation more robust -- as I've learned a good few techniques for what's needed here since the initial test setup was created

**Comment by NullVoxPopuli** [comment]
This is no longer needed, apologies. Your work was valuable towards landing eslint 9 support though!

**Pull request closed without merging**
