### PR TITLE
chore(internal):  add additional tests

### PR DESCRIPTION
**Pull request by k-teplyakov**
Additional tests in support of #474 
Based on #475 and #501

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
most excellent! thank you!!! <3

**Comment by NullVoxPopuli** [comment]
yup, just merged!

**Comment by k-teplyakov** [comment]
@NullVoxPopuli is it possible to make new release? I really need that fix :)

**Comment by NullVoxPopuli** [comment]
yeah, the release automation was supposed to do it -- but it was skipped for some reason :upside_down_face: gonna look in to that

**Pull request merged**
